version: "3.9"
services:
  encodecmae:
    image: encodecmae
    container_name: encodecmae-train
    volumes:
      - /home/lpepino/encodecmae:/workspace/encodecmae
      - /mnt/ssd4T/datasets:/workspace/datasets
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0','1']
            capabilities: [gpu]
